---
- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt: 
        update_cache: yes

    - name: Install required packages
      apt: 
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
        state: present

    - name: Install containerd
      apt: 
        name: containerd
        state: present

    - name: Create containerd config directory
      file:
        path: /etc/containerd
        state: directory

    - name: Create containerd root directory
      file:
        path: /data/containerd
        state: directory

    - name: Create containerd config file
      template:
        src: containerd_config.toml
        dest: /etc/containerd/config.toml 

    - name: Ensure the containerd modules file
      file:
        path: /etc/modules-load.d/containerd.conf
        state: touch

    - name: Add the kernel modules to containerd config
      lineinfile:
        path: /etc/modules-load.d/containerd.conf
        line:
          - "overlay"
          - "br_netfilter"

    - name: Load overlay module
      shell: modprobe overlay
      changed_when: false

    - name: Load br_netfilter module
      shell: modprobe br_netfilter
      changed_when: false

    - name: Start and enable containerd service
      service:
        name: containerd
        state: started
        enabled: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes

    - name: Restart containerd service
      service:
        name: containerd
        state: restarted